version: '2.3'
services:

# mysql
  wso2iot-mysql:
    image: mysql:5.7.20
    container_name: wso2iot-mysql
    hostname: wso2iot-mysql
    ports:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql/scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-uroot", "-proot"]
      interval: 10s
      timeout: 60s
      retries: 5
    networks:
        default:
            ipv4_address: 172.18.0.2

# base
# add base image creation

#  wso2iot-base:
#    build: 
#        context: ../dockerfiles/base
#        dockerfile: Dockerfile
#    image: wso2iot-base:3.3.0


# broker
# update broker to build from Dockerfile and comment the image

  wso2iot-broker:
    build: 
        context: ../dockerfiles/broker
        dockerfile: Dockerfile
    image: wso2iot-broker:3.3.0
    container_name: wso2iot-broker
    hostname: wso2iot-broker
    ports:
      - "9446:9446"
      - "5675:5675"
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9446"]
      interval: 10s
      timeout: 120s
      retries: 5
    depends_on:
      wso2iot-mysql:
        condition: service_healthy
    volumes:
      - ./broker:/home/wso2carbon/volumes/wso2/broker
    networks:
        default:
            ipv4_address: 172.18.0.5
    extra_hosts:
        - "www.dev.wso2.local:172.18.0.5"

# analytics
# update analytics to build from Dockerfile and comment the image

  wso2iot-analytics:
    build: 
        context: ../dockerfiles/analytics
        dockerfile: Dockerfile
    image: wso2iot-analytics:3.3.0
    container_name: wso2iot-analytics
    hostname: wso2iot-analytics
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "https://localhost:9445/carbon/admin/login.jsp"]
      interval: 10s
      timeout: 120s
      retries: 5
    depends_on:
      wso2iot-mysql:
        condition: service_healthy
    volumes:
      - ./analytics:/home/wso2carbon/volumes/wso2/analytics
    ports:
      - "9445:9445"
    networks:
        default:
            ipv4_address: 172.18.0.4
    extra_hosts:
        - "www.dev.wso2.local:172.18.0.4"

# iot-server
# Update iot server to build from Dockerfile and comment the image

  wso2iot-server:
    build:
        context: ../dockerfiles/iot-server
        dockerfile: Dockerfile    
    image: wso2iot-server:3.3.0
    container_name: wso2iot-server
    hostname: wso2iot-server
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "https://localhost:9443/carbon/admin/login.jsp"]
      interval: 10s
      timeout: 120s
      retries: 5
    depends_on:
      wso2iot-mysql:
        condition: service_healthy
    volumes:
      - ./iot-server:/home/wso2carbon/volumes
    ports:
      - "9443:9443"
    links:
      - wso2iot-mysql
    networks:
        default:
            ipv4_address: 172.18.0.3
    extra_hosts:
        - "www.dev.wso2.local:172.18.0.3"

networks:
    default:    
        ipam:
            driver: default
            config:
                - subnet: 172.18.0.0/24
                  ip_range: 172.18.0.0/24
                  gateway: 172.18.0.254
